config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'dashboard/show'
  # resources :covid_api_data
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  match 'api/retrieve/data', to: 'api#retrieve_covid_data', via: [:get]
  match 'api/update/data', to: 'api#update_data_with_symptoms', via: [:put]

  get 'retrieve_data', to: 'welcome#retrieve_data'
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get 'dashboard' => 'dashboard#show'
  get 'logout' => 'logout#logout'#, via: :destroy
end

app/models/covid_api_data.rb
class CovidApiData < ApplicationRecord
end

app/controllers/covid_api_data_controller.rb
class CovidApiDataController < ApplicationController
  before_action :set_covid_api_data, only: [:show, :edit, :update, :destroy]

  # GET /covid_api_data
  # GET /covid_api_data.json
  def index
    @covid_api_data = CovidApiData.all
  end

  # GET /covid_api_data/1
  # GET /covid_api_data/1.json
  def show
  end

  # GET /covid_api_data/new
  def new
    @covid_api_data = CovidApiData.new
  end

  # GET /covid_api_data/1/edit
  def edit
  end

  # POST /covid_api_data
  # POST /covid_api_data.json
  def create
    @covid_api_data = CovidApiData.new(covid_api_data_params)

    respond_to do |format|
      if @covid_api_data.save
        format.html { redirect_to @covid_api_data, notice: 'Covid api data was successfully created.' }
        format.json { render :show, status: :created, location: @covid_api_data }
      else
        format.html { render :new }
        format.json { render json: @covid_api_data.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /covid_api_data/1
  # PATCH/PUT /covid_api_data/1.json
  def update
    respond_to do |format|
      if @covid_api_data.update(covid_api_data_params)
        format.html { redirect_to @covid_api_data, notice: 'Covid api data was successfully updated.' }
        format.json { render :show, status: :ok, location: @covid_api_data }
      else
        format.html { render :edit }
        format.json { render json: @covid_api_data.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /covid_api_data/1
  # DELETE /covid_api_data/1.json
  def destroy
    @covid_api_data.destroy
    respond_to do |format|
      format.html { redirect_to covid_api_data_url, notice: 'Covid api data was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_covid_api_data
      @covid_api_data = CovidApiData.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def covid_api_data_params
      params.require(:covid_api_data).permit(:payload)
    end
end

app/helpers/covid_api_data_helper.rb
module CovidApiDataHelper
end

app/views/covid_api_data/_form.html.erb
<%= form_with(model: covid_api_ddata, local: true) do |form| %>
  <% if covid_api_ddata.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(covid_api_ddata.errors.count, "error") %> prohibited this covid_api_ddata from being saved:</h2>

      <ul>
        <% covid_api_ddata.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :payload %>
    <%= form.text_field :payload %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/covid_api_data/edit.html.erb
<h1>Editing Covid Api Ddata</h1>

<%= render 'form', covid_api_ddata: @covid_api_ddata %>

<%= link_to 'Show', @covid_api_ddata %> |
<%= link_to 'Back', covid_api_data_path %>

app/views/covid_api_data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Covid Api Data</h1>

<table>
  <thead>
    <tr>
      <th>Payload</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @covid_api_data.each do |covid_api_ddata| %>
      <tr>
        <td><%= covid_api_ddata.payload %></td>
        <td><%= link_to 'Show', covid_api_ddata %></td>
        <td><%= link_to 'Edit', edit_covid_api_ddata_path(covid_api_ddata) %></td>
        <td><%= link_to 'Destroy', covid_api_ddata, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Covid Api Ddata', new_covid_api_ddata_path %>

app/views/covid_api_data/new.html.erb
<h1>New Covid Api Ddata</h1>

<%= render 'form', covid_api_ddata: @covid_api_ddata %>

<%= link_to 'Back', covid_api_data_path %>

app/views/covid_api_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Payload:</strong>
  <%= @covid_api_ddata.payload %>
</p>

<%= link_to 'Edit', edit_covid_api_ddata_path(@covid_api_ddata) %> |
<%= link_to 'Back', covid_api_data_path %>