config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'dashboard/show'
  # resources :covid_api_data
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  match 'api/retrieve/data', to: 'api#retrieve_covid_data', via: [:get]
  match 'api/update/data', to: 'api#update_data_with_symptoms', via: [:put]

  get 'retrieve_data', to: 'welcome#retrieve_data'
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get 'dashboard' => 'dashboard#show'
  get 'logout' => 'logout#logout'#, via: :destroy
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :current_user

  def index
  end

  def retrieve_data
    if params[:location].to_s.present?
      location = params[:location].downcase
      host = Rails.env.production? ? "https://ncicloud.live" : "http://localhost:3000"
      url="#{host}/api/retrieve/data?location=#{location}" #this is hitting our API in API controller
      response = HTTParty.get(url)
      @responsebody = JSON.parse(response.body)

      if !@responsebody.empty?
        @active = @responsebody.map { |r| [r["Date"], r["Active"]] }
        @deaths = @responsebody.map { |r| [r["Date"], r["Deaths"]] }
        @symptoms_count = @responsebody.last["symptoms_count"]
      end
      
      respond_to do |format|
        format.js
      end
      # render json: @responsebody, status: :ok
    else
      redirect_to root_url, alert: "Location was empty"
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_chart.html.erb
<% if !@responsebody.empty?%>
  <p>Number of users declaring symptoms today: <%= @symptoms_count %></p>
  <br>
  <div id="chart_per_day" class="tab-pane fade in active">
    <%= line_chart [ {name: "Active", data: @active}, {name: "Deaths", data: @deaths}], 
    title: "COVID-19: Cases by day", xtitle: "Date", ytitle: "Cases", 
    width: "1200", height: "500px", colors: ["#008000", "#b00"] %>
  </div>
<% else %>
  <p>Unfortunately there is no data yet recorded for that country</p>
<% end %>

app/views/welcome/index.html.erb
<div class="jumbotron">
    <a href="#"><img src="https://i.ibb.co/VBrVj34/PGCAS.png" alt="COVID-19" width="150"></a>
  <h1>COVID-19 RISK Service</h1>
  <%= form_tag(retrieve_data_path, method: "get", remote: true) do %>
  <%= label_tag(:location, "Retrieve Covid-19 Data for your country:") %>
  <%= select_tag "location", options_from_collection_for_select(ISO3166::Country.all.sort, "alpha2", "name") %>
  <%= submit_tag("Search") %>
  <span class="glyphicon glyphicon-search"></span>
<% end %>
<br></div>

<br><br>
<div id="charts_div" class="tab-content">
  <div id="chart_per_day" class="tab-pane fade in active"></div>
</div>

app/views/welcome/retrieve_data.js.erb
$("#charts_div").html("<%= j render(partial: 'chart') %>");